apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "15"
    services: "10"
    persistentvolumeclaims: "10"
    
---
apiVersion: v1
kind: LimitRange
metadata:
  name: staging-limits
spec:
  limits:
  - type: Container
    default:
      cpu: "300m"
      memory: "384Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "1"
      memory: "1Gi"
    min:
      cpu: "50m"
      memory: "64Mi" 