apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  use-forwarded-headers: "true"
  proxy-buffer-size: "32k"
  proxy-body-size: "100m"
  client-header-buffer-size: "32k"
  # Staging-specific settings
  keep-alive-requests: "500"
  max-worker-connections: "2048"
  http2-max-field-size: "32k"
  ssl-protocols: "TLSv1.2 TLSv1.3" 