apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
# Cert Manager Installation
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: v1.13.3
  targetNamespace: cert-manager
  valuesContent: |-
    installCRDs: true
    global:
      leaderElection:
        namespace: cert-manager
    prometheus:
      enabled: false
    webhook:
      timeoutSeconds: 30